version: '3.4'

networks:
  dev:
    driver: bridge

services:   
  server:
    image: simonnyvall/backend:1.0
    depends_on:
      - "redis"
    container_name: server_container
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - Redis=redis_db:6379
    networks:
      - dev

  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev
volumes:
  app_data:
