version: '3.4'

networks:
  dev:
    driver: bridge

services:   
  server:
    image: simonnyvall/backend:1.0
    depends_on:
      - "seq"
    container_name: backend_nyblog
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - dev

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341
    environment:
      ACCEPT_EULA: Y
volumes:
  app_data:
